### ISSUE TITLE
the file icon needs margin

### ISSUE THREAD

**Issue by sidbelbase** [misolori/vscode-fluent-icons#13]
![image](https://user-images.githubusercontent.com/23023761/110658927-35361800-81ea-11eb-8509-608595b82811.png)
this `explorer icon` showing overlapping files might need little spacing between the front one and the other below them, what do you think?

OR

just file icon without any files below might look good, given that all the icons give a "singular vibe" why not do that with explorer icon too? That's just my thought :)

**Comment by misolori** [comment]
Thanks for the suggestion! There are other icons that have the same "overlay" so that fits within that pattern:

![image](https://user-images.githubusercontent.com/35271042/110720672-d9589880-81c3-11eb-8da4-e422011767b1.png)

![image](https://user-images.githubusercontent.com/35271042/110720695-e2496a00-81c3-11eb-94b9-6460f46f724c.png)

**Comment by sidbelbase** [comment]
nvm, I thought a margin between them would look cool. Anyway great icon taste. Keep polishing.

**Comment by misolori** [comment]
Thanks! I'll go ahead an close this one out, feel free to file another issue if you encounter any bugs.
